version: '3'

services:
  redis:
    image: redis
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flaskvue
      MYSQL_USER: flaskvue
      MYSQL_PASSWORD: secret
  web:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - "5555:5000"
    volumes:
      - .:/code
      - logvolume:/var/log
    links:
      - redis
    environment:
      FLASK_APP: app
      FLASK_ENV: development

volumes:
  datavolume:
  logvolume:
